default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: korokdb_development

test:
  <<: *default
  database: korokdb_test

production:
  <<: *default
  database: korokdb_production
